short_name = "rlengine"
name = "Real Engine"
major = 9
minor = 4
patch = 6
status = "close-alpha"
module_config = ""
version_build = "VFM"
version_docs_url = "https://vkplay.ru/play/game/real-engine/"
website = "https://vkplay.ru/play/game/real-engine/"
docs = "9.4.6"
