short_name = "rlengine"
name = "Real Engine"
major = 1
minor = 3
patch = 6
status = "close-alpha"
module_config = ""
version_build = "VFM"
version_docs_url = "https://www.k1shm1sh-realengine.ru/documentation.html"
website = "https://www.k1shm1sh-realengine.ru"
docs = "1.3.6"
