short_name = "rlengine"
name = "Real Engine"
major = 28
minor = 4
patch = 6
status = "close-alpha"
module_config = ""
website = "https://vkplay.ru/play/game/real-engine/"
docs = "28.4.6"
build = "VFM"
