#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import editor_theme_builders

# Fonts
flist = Glob("#thirdparty/fonts/*.ttf")
flist.extend(Glob("#thirdparty/fonts/*.otf"))
flist.extend(Glob("#thirdparty/fonts/*.woff"))
flist.extend(Glob("#thirdparty/fonts/*.woff2"))
flist.sort()
env.CommandNoCache(
    "#editor/themes/builtin_fonts.gen.h",
    flist,
    env.Run(editor_theme_builders.make_fonts_header),
)

# Добавляем ВСЕ .cpp файлы из директории themes
cpp_files = Glob("*.cpp")
print("Compiling theme sources:", [str(f) for f in cpp_files])
env.add_source_files(env.editor_sources, cpp_files)
